level_1:
  time: 5000
  sequence: [ 'red' ]
level_2:
  time: 5000
  sequence: [ 'red', 'green' ]
level_3:
  time: 5000
  sequence: [ 'red', 'green', 'yellow' ]
level_4:
  time: 5000
  sequence: [ 'red', 'green', 'yellow', 'blue' ]
level_5:
  time: 5000
  sequence: [ 'red', 'green', 'yellow', 'blue' ]
